version: "3.4"

services:
    web:
        build:
            target: debug
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - DOTNET_USE_POLLING_FILE_WATCHER=1
        volumes:
            - ./Blog.Bll/Dto:/app/Blog.Bll/Dto
            - ./Blog.Bll/Exceptions:/app/Blog.Bll/Exceptions
            - ./Blog.Bll/Middlewares:/app/Blog.Bll/Middlewares
            - ./Blog.Bll/Services:/app/Blog.Bll/Services
            - ./Blog.Dal/Migrations:/app/Blog.Dal/Migrations
            - ./Blog.Dal/Models:/app/Blog.Dal/Models
            - ./Blog.Dal/Repositories:/app/Blog.Dal/Repositories
            - ./Blog.Web/Controllers:/app/Blog.Web/Controllers
            - ./Blog.Web/Mappings:/app/Blog.Web/Mappings
            - ./Blog.Web/ClientApp/src/app:/app/Blog.Web/ClientApp/src/app
            - ./vsdbg:/app/vsdbg
        entrypoint: tail -f /dev/null #make docker container running