version: "3.4"

services:
    web:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        volumes:
            - ./Blog.Web/ClientApp/src/app:/app/Blog.Web/ClientApp/src/app